
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sites?serverTimezone=UTC
    url: jdbc:p6spy:mysql://localhost:3306/sites?serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  thymeleaf:
    enabled: false
  security:
    basic:
      enable: false
    user:
      name: root
      password: admin

server:
  port: 8000

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  mapper-locations: classpath:mapper/*.xml
